name: Generate ASCII Artwork Dragon

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-artwork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: shellscript for  cowsay
        run: |
           chmod +x dragonscript.sh
           ./dragonscript.sh
        

      
